
print "// This file was autogenerated by the POWLutGenerator ( see Software/POWLutGenerator )"
print 

print "PROGMEM float sp_pow3LUT[] = {";

for i in range(0, 511):
	print "\t%ff," % pow((i/511.0), 3),;
	if i % 8 == 7:
		print

print "\t%ff\n};" % pow(1.0, 3);